import React from 'react';
import { Navigation } from '@/components/Navigation';
import { motion } from 'framer-motion';

const sections = [
  ['Important disclaimer', 'Silent Solidarity is an independent digital-expression project. It is not affiliated with, endorsed by, funded by, or acting on behalf of any protest organizer, participant, political party, government body, examination authority, educational institution, or media organization. Content is not legal, medical, security, or professional advice, and the site is not a source of live protest instructions.'],
  ['Acceptable use', 'You may use this site only for peaceful, lawful, good-faith expression. You must not post threats, calls for violence, harassment, hateful or discriminatory content, sexually explicit material, false statements presented as fact, spam, malware, impersonation, copyrighted material you lack rights to use, or content that violates applicable law or another person’s rights. Do not publish personal data, including phone numbers, addresses, email addresses, identity numbers, account details, or another person’s image or private information without their clear permission.'],
  ['Automated moderation', 'Submissions that pass the automated safety checks publish immediately. The checks look for profanity (including common evasions), threats or violence-related language, contact details, identity-number patterns, links, and obvious spam. Content matching a safety rule is rejected automatically and is not published. Automated filters can make mistakes and do not guarantee that every unsafe item will be caught. We may preserve limited technical records and take action where required by law or valid legal process.'],
  ['Your content and responsibility', 'You remain responsible for what you submit. By submitting, you confirm that you have the rights and permissions needed to share it and grant the site a non-exclusive, worldwide, royalty-free licence to host, display, reproduce, and moderate it for operating and promoting this service. Messages represent their authors’ views, not ours. We may preserve limited technical records, including IP address and submission time, for abuse prevention, security, and legal compliance.'],
  ['Privacy and location', 'Location is optional. Exact coordinates are not displayed publicly; the public map uses a randomized regional position and shows only the available locality, state, or country label. Do not treat this as anonymity or security advice. Avoid sharing information that could identify or endanger you or anyone else.'],
  ['No guarantee; governing law', 'The service is provided “as is” and “as available” without guarantees of uninterrupted access, accuracy, publication, or fitness for a particular purpose. To the extent permitted by applicable law, we are not liable for user content or reliance on it. These terms are intended to be read with applicable Indian law; mandatory consumer, privacy, and other legal rights are not excluded. If a provision is unenforceable, the rest remains effective.'],
  ['Contact and updates', 'For content, privacy, takedown, or legal requests, contact the site operator using the contact details published with the deployed service. We may update these terms and will post the revised version here. Continued use after publication means you accept the updated terms.'],
];

export default function LegalPage() {
  return <div className="min-h-screen bg-background relative pb-20"><Navigation /><div className="max-w-4xl mx-auto pt-28 sm:pt-32 px-4 sm:px-6"><motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-8 text-center"><h1 className="font-serif text-3xl sm:text-4xl text-white mb-3">Terms, safety & disclaimer</h1><p className="text-muted-foreground max-w-3xl mx-auto text-sm leading-relaxed">Effective 23 July 2026. These rules keep the vigil peaceful, respectful, and lawful. They are a practical template, not legal advice; have a qualified Indian lawyer review them before launch.</p></motion.div><div className="glass-panel p-5 sm:p-7 space-y-7">{sections.map(([title, text]) => <section key={title}><h2 className="text-lg text-white font-semibold mb-2">{title}</h2><p className="text-muted-foreground text-sm leading-relaxed">{text}</p></section>)}</div></div></div>;
}
